"""Current-season MLB pages; no embedded historical betting cards."""
from html import escape
from mlb.refresh import ROOT
from site_metadata import metadata
from nba.pipeline import read_json


def validation_html():
    report = read_json(ROOT/'docs/mlb/data/validation.json', {})
    if not report:return '<p>Model validation is awaiting its first completed training run.</p>'
    labels={'pitcher_strikeouts':'Pitcher strikeouts','pitcher_outs':'Pitcher outs','batter_hits':'Batter hits',
            'batter_total_bases':'Total bases','batter_home_runs':'Home runs','batter_rbis':'RBIs',
            'totals':'Game totals','h2h':'Moneylines','spreads':'Run lines'}
    parts=[f'''<p class="lead">Every market has an independent outcome check. These results measure probability accuracy, not betting profits.</p>
<section class="panel"><h2>What was tested</h2><p>{report['games']:,} completed games supply the history. Model weights use games through <strong>{report['training_through']}</strong>; model selection and probability calibration use the next period through <strong>{report['calibration_through']}</strong>. The untouched regular-season test runs <strong>{report['test_start']} to {report['test_end']}</strong>.</p><p>Rolling player and team features update before each test date using earlier dates only. Live features now include completed games through <strong>{report['input_through']}</strong>. Same-day results never enter a forecast.</p></section>''']
    for key,title in [('regular','Regular-season holdout'),('postseason',f"{report['postseason_year']} postseason audit")]:
        rows=[]
        for market,m in report.get(key,{}).items():
            if 'brier' not in m:continue
            skill=100*m['brier_skill']
            rows.append(f"<tr><th scope='row'>{labels[market]}</th><td>{m['games']}</td><td>{m['brier']:.4f}</td><td>{m['reference_brier']:.4f}</td><td>{skill:+.1f}%</td><td>{100*m['ece']:.1f} pp</td><td>{'Passed initial checks' if m['passed'] else 'Research only'}</td></tr>")
        parts.append(f'''<section class="section"><h2>{title}</h2><div class="mlb-table-scroll" tabindex="0" role="region" aria-label="{title} results"><table class="mlb-validation"><thead><tr><th>Market</th><th>Games</th><th>Model Brier ↓</th><th>Reference Brier ↓</th><th>Relative gain</th><th>Calibration gap ↓</th><th>Status</th></tr></thead><tbody>{''.join(rows)}</tbody></table></div></section>''')
    parts.append(f'''<div class="help"><h2>How to read these numbers</h2><p>Brier score is the average squared difference between a predicted probability and the result (0 or 1). Lower is better. The reference uses the training period’s overall outcome distribution, without player or matchup information. Relative gain compares the two scores; a negative gain means the model was worse. A small positive gain is not proof of a reliable advantage.</p><p>The calibration gap is the weighted difference between predicted and observed outcomes in ten probability buckets. Tests use fixed line grids, with several thresholds per forecast. Games are the number of distinct games; thresholds from the same game are correlated and are not independent trials. We have not established statistical significance.</p><p>Initial eligibility requires a lower Brier score than the reference, at least 150 regular-season games and a calibration gap no greater than 6 percentage points. Postseason checks require 30 games and at most 12 points. Those broader postseason limits reflect the small sample; they do not make playoff forecasts equally reliable.</p><p>The postseason audit used a separate earlier model: training through {report['postseason_training_through']}, calibration through {report['postseason_calibration_through']}. It never trained on the later regular-season holdout or on those playoff results. This is a limited historical stress test, not a validation of the current weights on future playoffs.</p>
<h2>What this does not establish</h2><p>We do not have timestamped historical book prices for this audit. There is no claimed historical return, win-rate-at-offered-odds, or proof that these forecasts beat the sportsbook market. Current picks are experimental estimates. A forward record begins with the archived forecast snapshots.</p><ul>{''.join('<li>'+escape(s)+'</li>' for s in report['limitations'])}</ul><p>Model version: <code>{escape(report['version'])}</code>. <a href="data/validation.json">Download the full validation report</a>.</p></div>''')
    return ''.join(parts)


def build(state):
    season = str(state['season'])
    label = season
    pages = [('index.html', 'MLB Overview', 'overview'), ('props/index.html', 'Player Props', 'props'),
             ('totals/index.html', 'Game Lines', 'lines'), ('picks.html', 'Model Picks', 'picks'),
             ('top.html', 'Market Watch', 'watch'), ('validation.html', 'Model Results', 'validation'),
             ('methods.html', 'MLB Methods', 'methods')]
    for filename, title, page in pages:
        path = ROOT / 'docs/mlb' / filename
        rel = '../..' if '/' in filename else '..'
        mlb = '..' if '/' in filename else '.'
        links = '<nav class="subnav" aria-label="MLB sections">' + ''.join(
            f'<a href="{mlb}/{f}"' + (' aria-current="page"' if f == filename else '') + f'>{t}</a>'
            for f,t,_ in pages if f != 'methods.html') + '</nav>'
        if page == 'overview':
            intro = '''<p class="lead">Follow the pennant race into October. Compare baseball prices with the matchup in view.</p>
<div class="actions"><a class="button primary" href="picks.html">See model picks →</a><a class="button" href="props/">Explore player forecasts →</a><a class="button" href="validation.html">Review model results →</a></div>
<div class="grid"><article class="panel"><h2>Pitcher and batter props</h2><p>Strikeouts, outs, hits, total bases, home runs and RBIs. Shop the same outcome across books.</p><a href="props/">Open props →</a></article><article class="panel"><h2>Game lines</h2><p>Moneylines, run lines and totals with de-vigged book prices and same-line consensus.</p><a href="totals/">Open game lines →</a></article><article class="panel"><h2>Market Watch</h2><p>Find prices that disagree with at least three other books at the same line.</p><a href="top.html">Explore disagreements →</a></article></div>
<section class="panel"><h2>Independent forecasts, visible checks</h2><p>Our models forecast six player props plus full-game totals, moneylines and run lines using prior games, player workload, opponent rates, bullpen usage and park context. Every forecast is checked against a chronological outcome test. Model Picks shows only offers meeting both the model and price checks; Market Watch tracks disagreement between books.</p><p>Probable starters remain provisional. Batter forecasts require that player in a published starting order. Playoff picks use a separate historical postseason check. Shorter outings, tactical substitutions and unmodeled injuries can still change the result.</p><a href="methods.html">How the models work →</a></section>
<section class="section"><h2>Upcoming games</h2><p class="muted">Official MLB schedule, next 45 days. Doubleheaders are matched by game time.</p><label>Season phase <select id="schedule-phase"><option value="">All games</option><option value="R">Regular season</option><option value="postseason">Postseason</option></select></label><div id="schedule" class="grid"></div></section>'''
        elif page == 'validation':
            intro = validation_html()
        elif page == 'methods':
            intro = '''<div class="help"><p class="lead">Independent baseball forecasts, current prices and a public record of model checks.</p>
<h2>Which games qualify</h2><p>We match The Odds API events to MLB’s official schedule using both teams and a start time within ten minutes. MLB game IDs distinguish doubleheaders. Only regular season (R), Wild Card (F), Division Series (D), Championship Series (L) and World Series (W) qualify. Spring training, exhibitions, All-Star games, postponed or suspended games, delayed starts, and unknown start times are excluded. Unconfirmed playoff matchups are not invented.</p>
<h2>Price comparisons</h2><p>Moneylines, run lines and totals refer to full games. We do not mix first-five-inning markets into them. Props cover pitcher strikeouts and outs, plus batter hits, total bases, home runs and RBIs. Margin removal needs both sides from the same book, event, player, market and line. Run-line pairs use opposite handicaps. Each book gets one vote in same-line consensus; duplicate conflicting quotes are withheld.</p><p>Market Watch compares an offer with at least three other paired books, excluding the quoted book itself. It identifies disagreement, not a validated expected profit. Integer lines can push; de-vigged market probabilities are conditional on a non-push result. Confirm your book’s listed-pitcher, participation, postponement and settlement rules before using a quote.</p>
<h2>What goes into a forecast</h2><p>Official MLB game-level box scores supply prior player and team outcomes. We use the previous season from August onward, including October, and the current season. We discard box-score season totals and compute every historical feature from earlier dates only. All games on a date share the same pre-date history, including doubleheaders.</p><p>Team features include the last 40 games of scoring and batting rates, bullpen runs per out, and bullpen pitches over the prior three days. Pitcher features include up to 15 starts, outs and pitch counts over the last five, strikeouts, walks, hits and home runs per batter faced, runs allowed and rest. Batter features use up to 60 games of plate appearances and event rates, recent starting-game opportunities and the published batting slot. Rates shrink toward fixed league-like priors when samples are small. Venue scoring uses up to 100 prior games, shrunk toward nine combined runs; it is not a fully isolated park effect.</p>
<h2>From a projection to a probability</h2><p>Each target compares a small gradient-boosted regression with a transparent rolling-rate baseline on a later calibration period. The lower mean-squared-error candidate supplies the mean. Count outcomes use Poisson distributions when dispersion is negligible and negative binomial distributions when variability is larger. Pitcher outs use a discretized normal distribution. Isotonic calibration adjusts the cumulative probabilities using the calibration period; a 2% raw-distribution component avoids absolute certainty in the tails.</p><p>Two team-run distributions form a full-game score matrix. Tied final scores are removed and the remainder normalized. That approximation prices moneylines, run lines and totals; it does not simulate every extra inning or every pitcher change. Displayed projections are the means of the final calibrated distributions, so they can differ from the raw regression mean.</p><p>Win and push probabilities are separate. At decimal odds D, expected return per dollar is P(win) × (D − 1) − P(loss). Fair American odds and the displayed probability edge use P(win) / (1 − P(push)), allowing comparison with a book’s break-even price. Model probability itself is the unconditional win chance. The model never uses current book prices as a feature.</p>
<h2>How an offer becomes a Model Pick</h2><p>The relevant regular-season or postseason market must pass the checks on <a href="validation.html">Model Results</a>. Both probable starters must be known and have at least three earlier starts; both teams need ten earlier games. A batter needs 50 earlier plate appearances and a unique match to a complete published starting order. MLB’s published order can still change before first pitch.</p><p>The game must start within 24 hours; the quote and model-input check must be no more than 90 minutes old. At least two books must have paired outcomes at the same line, and the evaluated quote itself must be paired. The line must fall within the tested range. We require at least 3% estimated return and a 3-percentage-point advantage over the quoted break-even probability. Discrepancies above 30% estimated return are withheld for manual review. We select the best available price and one offer per player, market and game. Different selected markets can still be correlated.</p><p>These are experimental model picks, not a proven profitable system. When a check fails, the board explains why. A forecast may remain visible for research while its pick eligibility is withheld.</p>
<h2>Starters, batting orders and limitations</h2><p>Probable pitchers come from the current official schedule. Published orders come from the upcoming game’s box score and are accepted only with nine unique original slots and no recorded game action. We do not invent a lineup or forecast an unmatched player. Historical evaluation uses the actual starter and original starting order because archived pregame announcements are unavailable; late scratches and lineup uncertainty are therefore not fully captured by the audit.</p><p>The model includes a postseason indicator and recent workload. Its prior-postseason audit is small. Handedness, forecast weather, injuries, umpires and explicit pinch-hit or playoff-hook decisions are not modeled. Those factors can invalidate an apparent edge. Check current availability and your sportsbook’s settlement rules.</p><p>Separate descriptive season context uses regular-season totals through yesterday’s Eastern date. This display excludes postseason stats; the game-level model history includes completed postseason games. ERA and K/9 use recorded outs: 5.2 innings is 17 outs.</p>
<h2>Freshness and coverage</h2><p>Automated runs refresh history and retrain when the daily cutoff or model code changes. Rolling features include completed games through yesterday Eastern; weights stay earlier than the calibration and test periods. The visible dates distinguish these two kinds of updating. Markets refresh twice daily; comparison quotes expire after 12 hours, model picks after 90 minutes, and all offers at first pitch. Open boards refresh every five minutes. A stale or failed model refresh withholds model picks while current market comparisons can remain available.</p><p>Prop requests cover the next 24 hours, capped at 20 games per run. Skipped games are reported. Early runs can have no hitter forecasts because batting orders have not yet been published. Season context expires after 36 hours or a failed statistics refresh. Forecast snapshots preserve the quoted price, inputs, model version and eligibility decision for forward review.</p>
<h2>Sources</h2><p><a href="https://www.mlb.com/schedule">MLB schedule</a> · <a href="https://www.mlb.com/postseason">MLB postseason</a> · <a href="https://www.mlb.com/stats/">MLB statistics</a> · <a href="https://the-odds-api.com/sports/mlb-odds.html">The Odds API MLB coverage</a></p></div>'''
        else:
            lead = {'props':'Compare pitcher strikeouts and outs, plus batter hits, total bases, home runs and RBIs.',
                    'lines':'Full-game totals, run lines and moneylines with probable-pitcher context and postseason labels.',
                    'picks':'Experimental selections from our independent models. Each offer must pass the market validation, player availability, freshness and price checks. Estimated returns are not guaranteed profits.',
                    'watch':'Offers that differ from at least three other books at the same line. These are research leads, not validated model picks.'}[page]
            intro = f'''<p class="lead">{lead}</p>
<div class="filters"><label>Player or matchup<input id="search" type="search" placeholder="Search MLB…"></label><label>Market<select id="market"><option value="">All markets</option></select></label><label>Sportsbook<select id="book"><option value="">All books</option></select></label><label>Game<select id="game"><option value="">All games</option></select></label><label>Season phase<select id="phase"><option value="">All phases</option><option value="R">Regular season</option><option value="postseason">Postseason</option><option value="F">Wild Card</option><option value="D">Division Series</option><option value="L">Championship Series</option><option value="W">World Series</option></select></label></div>
<div class="checks"><label><input type="checkbox" id="best" checked> Best price at each line</label><button id="reset">Reset filters</button></div><p id="result-count" role="status"></p><div id="results" class="prop-grid"></div><button id="more" hidden>Show more</button>
<section class="help section"><h2>Read the comparison</h2><p>Book probability is the break-even rate at that price. Paired fair probability removes the book’s margin. Consensus uses distinct books at the same line. Season statistics describe past performance and do not qualify model picks.</p><a href="{mlb}/methods.html">MLB methods and limitations →</a></section>'''
        body = f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} | Fourth &amp; Value</title>
{metadata(path, title+' | Fourth & Value', 'MLB regular-season and postseason odds, player props, game lines and market consensus from Fourth & Value.')}
<link rel="stylesheet" href="{rel}/assets/site.css"><link rel="stylesheet" href="{rel}/assets/mlb.css?v=1"><link rel="icon" href="{rel}/assets/logo.svg"></head><body><a class="skip-link" href="#main">Skip to content</a><div id="nav-root"></div><script src="{rel}/nav.js?v=42"></script>
<main class="wrap" id="main" data-mlb-page="{page}" data-feed="{mlb}/data/latest.json">{links}<p class="eyebrow">MLB · {label}</p><h1>{title}</h1>
<div class="notice" id="feed-status" role="status"><strong>MLB baseball market snapshot</strong><p>Last successful check: {escape(str(state.get('last_success_at') or 'Not yet checked'))}. Enable JavaScript to view current quote availability.</p></div>
<p class="muted" id="history-status"></p><section class="panel mlb-model-summary" id="model-status" aria-label="Model coverage"></section>{intro}<footer>Fourth &amp; Value · <a href="{rel}/terms.html">Terms &amp; privacy</a> · <a href="{rel}/videos/">Videos</a></footer></main><script src="{rel}/assets/mlb.js?v=2" defer></script></body></html>'''
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body)
